version: '3.7'
services:
  datagora_datatlas_front:
    build:
      context: .
      dockerfile: Dockerfile.dev
      #target: dev
    restart: always
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env

    command: npm start
    stdin_open: true
